from django.urls import path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("vps-direct-sale/", views.vps_direct_sale, name="vps_direct_sale"),
    path("offer/", views.offer, name="offer"),
    path("privacy/", views.privacy, name="privacy"),
    path("terms/", views.terms, name="terms"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("update-email/", views.update_email, name="update_email"),
    path("cancel-autopay/", views.cancel_autopay, name="cancel_autopay"),
    path(
        "cabinet/api/payments/",
        views.cabinet_payments_history,
        name="cabinet_payments_history",
    ),
    path("confirm-email/<path:token>/", views.confirm_email, name="confirm_email"),
    path(
        "support/tickets/create/",
        views.create_support_ticket,
        name="create_support_ticket",
    ),
    path(
        "support/tickets/<int:ticket_id>/messages/",
        views.create_support_ticket_message,
        name="create_support_ticket_message",
    ),
    path(
        "support/tickets/<int:ticket_id>/messages-json/",
        views.support_ticket_messages_json,
        name="support_ticket_messages_json",
    ),
    path(
        "support/tickets/<int:ticket_id>/close/",
        views.close_support_ticket,
        name="close_support_ticket",
    ),
    path(
        "support/attachments/<int:attachment_id>/",
        views.support_attachment,
        name="support_attachment",
    ),
    path("api/cabinet/devices/", views.cabinet_devices, name="cabinet_devices"),
    path(
        "api/cabinet/devices/delete/",
        views.cabinet_device_delete,
        name="cabinet_device_delete",
    ),
    path("support-admin/login/", views.support_admin_login, name="support_admin_login"),
    path(
        "support-admin/logout/", views.support_admin_logout, name="support_admin_logout"
    ),
    path("support-admin/", views.support_admin_tickets, name="support_admin_tickets"),
    path(
        "support-admin/tickets-json/",
        views.support_admin_tickets_json,
        name="support_admin_tickets_json",
    ),
    path(
        "support-admin/api/stats/",
        views.support_admin_api_stats,
        name="support_admin_api_stats",
    ),
    path(
        "support-admin/api/acquisition/",
        views.support_admin_api_acquisition,
        name="support_admin_api_acquisition",
    ),
    path(
        "support-admin/api/ad-spends/",
        views.support_admin_api_ad_spends,
        name="support_admin_api_ad_spends",
    ),
    path(
        "support-admin/api/stats/source-users/",
        views.support_admin_api_stats_source_users,
        name="support_admin_api_stats_source_users",
    ),
    path(
        "support-admin/api/cohort-stats/",
        views.support_admin_api_cohort_stats,
        name="support_admin_api_cohort_stats",
    ),
    path(
        "support-admin/api/user-payments/",
        views.support_admin_api_user_payments,
        name="support_admin_api_user_payments",
    ),
    path(
        "support-admin/api/user-traffic/",
        views.support_admin_api_user_traffic,
        name="support_admin_api_user_traffic",
    ),
    path(
        "support-admin/api/referrals/",
        views.support_admin_api_referrals,
        name="support_admin_api_referrals",
    ),
    path(
        "support-admin/api/payment-info/",
        views.support_admin_api_payment_info,
        name="support_admin_api_payment_info",
    ),
    path(
        "support-admin/api/payments/",
        views.support_admin_api_payments,
        name="support_admin_api_payments",
    ),
    path(
        "support-admin/api/subscription-manage/",
        views.support_admin_api_subscription_manage,
        name="support_admin_api_subscription_manage",
    ),
    path(
        "support-admin/api/runtime-settings/",
        views.support_admin_api_runtime_settings,
        name="support_admin_api_runtime_settings",
    ),
    path(
        "support-admin/api/referral-antifraud/",
        views.support_admin_api_referral_antifraud,
        name="support_admin_api_referral_antifraud",
    ),
    path(
        "support-admin/api/antiabuse/",
        views.support_admin_api_antiabuse,
        name="support_admin_api_antiabuse",
    ),
    path(
        "support-admin/api/antiabuse-bulk/",
        views.support_admin_api_antiabuse_bulk,
        name="support_admin_api_antiabuse_bulk",
    ),
    path(
        "support-admin/api/antiabuse-backfill/",
        views.support_admin_api_antiabuse_backfill,
        name="support_admin_api_antiabuse_backfill",
    ),
    path(
        "support-admin/api/ipguard-alerts/",
        views.support_admin_api_ipguard_alerts,
        name="support_admin_api_ipguard_alerts",
    ),
    path(
        "support-admin/api/referral-block/",
        views.support_admin_api_referral_block,
        name="support_admin_api_referral_block",
    ),
    path(
        "support-admin/api/recurrents/",
        views.support_admin_api_recurrents,
        name="support_admin_api_recurrents",
    ),
    path(
        "support-admin/api/audit-log/",
        views.support_admin_api_audit_log,
        name="support_admin_api_audit_log",
    ),
    path(
        "support-admin/api/user-timeline/",
        views.support_admin_api_user_timeline,
        name="support_admin_api_user_timeline",
    ),
    path(
        "support-admin/api/rwms-sync/",
        views.support_admin_api_rwms_sync,
        name="support_admin_api_rwms_sync",
    ),
    path(
        "support-admin/api/direct-message/",
        views.support_admin_api_direct_message,
        name="support_admin_api_direct_message",
    ),
    path(
        "support-admin/api/segments/",
        views.support_admin_api_segments,
        name="support_admin_api_segments",
    ),
    path(
        "support-admin/api/broadcasts/",
        views.support_admin_api_broadcasts,
        name="support_admin_api_broadcasts",
    ),
    path(
        "support-admin/api/bulk/",
        views.support_admin_api_bulk,
        name="support_admin_api_bulk",
    ),
    path(
        "support-admin/api/promocodes/",
        views.support_admin_api_promocodes,
        name="support_admin_api_promocodes",
    ),
    path(
        "support-admin/api/promo-cohort/",
        views.support_admin_api_promo_cohort,
        name="support_admin_api_promo_cohort",
    ),
    path(
        "support-admin/api/accounts/",
        views.support_admin_api_accounts,
        name="support_admin_api_accounts",
    ),
    path(
        "support-admin/api/traffic-nodes/",
        views.support_admin_api_traffic_nodes,
        name="support_admin_api_traffic_nodes",
    ),
    path(
        "support-admin/api/node-traffic/",
        views.support_admin_api_node_traffic,
        name="support_admin_api_node_traffic",
    ),
    path(
        "support-admin/api/ripe-keys/",
        views.support_admin_api_ripe_keys,
        name="support_admin_api_ripe_keys",
    ),
    path(
        "support-admin/api/censor-checks/",
        views.support_admin_api_censor_checks,
        name="support_admin_api_censor_checks",
    ),
    path(
        "support-admin/api/censor-check-runs/",
        views.support_admin_api_censor_check_runs,
        name="support_admin_api_censor_check_runs",
    ),
    path(
        "support-admin/api/reply-templates/",
        views.support_admin_api_reply_templates,
        name="support_admin_api_reply_templates",
    ),
    path(
        "support-admin/api/config-templates/",
        views.support_admin_api_config_templates,
        name="support_admin_api_config_templates",
    ),
    path(
        "support-admin/api/config-pins/",
        views.support_admin_api_config_pins,
        name="support_admin_api_config_pins",
    ),
    path(
        "support-admin/api/ua-rules/",
        views.support_admin_api_ua_rules,
        name="support_admin_api_ua_rules",
    ),
    path(
        "support-admin/api/node-scripts/",
        views.support_admin_api_node_scripts,
        name="support_admin_api_node_scripts",
    ),
    path(
        "support-admin/api/node-provision/",
        views.support_admin_api_node_provision,
        name="support_admin_api_node_provision",
    ),
    path(
        "support-admin/api/node-provision/detail/",
        views.support_admin_api_node_provision_detail,
        name="support_admin_api_node_provision_detail",
    ),
    path(
        "support-admin/api/infra-servers/",
        views.support_admin_api_infra_servers,
        name="support_admin_api_infra_servers",
    ),
    path(
        "support-admin/api/infra-server-detail/",
        views.support_admin_api_infra_server_detail,
        name="support_admin_api_infra_server_detail",
    ),
    path(
        "support-admin/api/infra-telemetry/",
        views.support_admin_api_infra_telemetry,
        name="support_admin_api_infra_telemetry",
    ),
    path(
        "support-admin/api/infra-settings/",
        views.support_admin_api_infra_settings,
        name="support_admin_api_infra_settings",
    ),
    # Bootstrap-API установки нод: публичные ручки для обёртки на сервере,
    # отвечают только на доменах из NODE_BOOTSTRAP_DOMAINS
    path(
        "node-bootstrap/runner/",
        views.node_bootstrap_runner,
        name="node_bootstrap_runner",
    ),
    path(
        "node-bootstrap/claim/",
        views.node_bootstrap_claim,
        name="node_bootstrap_claim",
    ),
    path(
        "node-bootstrap/script/",
        views.node_bootstrap_script,
        name="node_bootstrap_script",
    ),
    path(
        "node-bootstrap/progress/",
        views.node_bootstrap_progress,
        name="node_bootstrap_progress",
    ),
    path(
        "node-bootstrap/complete/",
        views.node_bootstrap_complete,
        name="node_bootstrap_complete",
    ),
    path(
        "support-admin/tickets/<int:ticket_id>/",
        views.support_admin_ticket_detail,
        name="support_admin_ticket_detail",
    ),
    path(
        "support-admin/tickets/<int:ticket_id>/messages/",
        views.support_admin_create_message,
        name="support_admin_create_message",
    ),
    path(
        "support-admin/tickets/<int:ticket_id>/messages-json/",
        views.support_admin_ticket_messages_json,
        name="support_admin_ticket_messages_json",
    ),
    path(
        "support-admin/tickets/<int:ticket_id>/close/",
        views.support_admin_close_ticket,
        name="support_admin_close_ticket",
    ),
    path(
        "support-admin/tickets/<int:ticket_id>/reopen/",
        views.support_admin_reopen_ticket,
        name="support_admin_reopen_ticket",
    ),
    path(
        "support-admin/tickets/<int:ticket_id>/delete/",
        views.support_admin_delete_ticket,
        name="support_admin_delete_ticket",
    ),
    path(
        "support-admin/attachments/<int:attachment_id>/",
        views.support_admin_attachment,
        name="support_admin_attachment",
    ),
    path("pay/", views.pay, name="pay"),
    path(
        "payment/status/<str:token>/",
        views.payment_status,
        name="payment_status",
    ),
    path(
        "payment/retry/<str:token>/",
        views.payment_retry,
        name="payment_retry",
    ),
    path(
        "payment/status/<str:token>/json/",
        views.payment_status_json,
        name="payment_status_json",
    ),
    path(
        "payment/status/<str:token>/active-json/",
        views.payment_status_active_json,
        name="payment_status_active_json",
    ),
    path("login/", views.login, name="login"),
    path("login/send-link/", views.send_magic_link, name="send_magic_link"),
    path("login/google/", views.login_with_google, name="google_login"),
    path("login/google/callback/", views.auth_by_google_callback, name="google_auth"),
    path("login/yandex/", views.login_with_yandex, name="yandex_login"),
    path("login/yandex/callback/", views.auth_by_yandex_callback, name="yandex_auth"),
    path(
        "login/telegram-auth/",
        views.auth_by_telegram_widget,
        name="telegram_widget_auth",
    ),
    path("tg-webapp/", views.telegram_webapp_entry, name="telegram_webapp_entry"),
    path(
        "tg-webapp/auth/",
        views.auth_by_telegram_webapp,
        name="telegram_webapp_auth",
    ),
    path("login/magic/<uuid:token>/", views.auth_by_magic_link, name="magic_auth"),
    path(
        "login/purchase/<str:token>/",
        views.auth_by_purchase_link,
        name="purchase_auth",
    ),
    path(
        "login/telegram/<str:token>/", views.auth_by_telegram_link, name="telegram_auth"
    ),
    path("logout/", views.logout, name="logout"),
    path("robots.txt", views.robots_txt, name="robots_txt"),
    path("manifest.json", views.dynamic_manifest),
    # Путь к сервис-воркеру
    path(
        "sw.js",
        TemplateView.as_view(
            template_name="pwa/sw.js", content_type="application/javascript"
        ),
        name="sw",
    ),
]
