import sys
import dj_database_url
from pathlib import Path
from urllib.parse import urlparse
from importlib.util import find_spec
from decouple import config

"""
Django settings for web_app project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def csv_list(value):
    return [item.strip() for item in value.split(",") if item.strip()]


def normalize_domain_entry(value):
    candidate = value.strip()
    if not candidate:
        return ""

    if "://" in candidate:
        parsed = urlparse(candidate)
        candidate = parsed.netloc or parsed.path

    return candidate.split(":", 1)[0].lower().strip("/")


def csv_domains(value):
    return [
        normalized
        for item in value.split(",")
        if (normalized := normalize_domain_entry(item))
    ]


PROMO_DOMAINS = config(
    "PROMO_DOMAINS",
    default="localhost,127.0.0.1",
    cast=csv_domains,
)
NEUTRAL_DOMAINS = config(
    "NEUTRAL_DOMAINS",
    default="",
    cast=csv_domains,
)
CABINET_DOMAINS = config(
    "CABINET_DOMAINS",
    default="localhost,127.0.0.1",
    cast=csv_domains,
)
DEFAULT_CABINET_DOMAIN = config(
    "DEFAULT_CABINET_DOMAIN",
    default="http://localhost:8000"
)
PWA_MIRROR_SOURCE_URL = config("PWA_MIRROR_SOURCE_URL", default="")
TG_BOT_USERNAME = config('TG_BOT_USERNAME', default='monkeyislandvpnbot')
TELEGRAM_AUTH_BOT_TOKEN = config(
    "TELEGRAM_AUTH_BOT_TOKEN",
    default=config("MI_VPN_BOT_TOKEN", default=""),
)
SITE_TRIAL_PERIOD_DAYS = config("SITE_TRIAL_PERIOD_DAYS", default=7, cast=int)
SITE_REFERRAL_TRIAL_PERIOD_DAYS = config(
    "SITE_REFERRAL_TRIAL_PERIOD_DAYS",
    default=15,
    cast=int,
)
USE_NEW_SETUP_FLOW = config("USE_NEW_SETUP_FLOW", default=True, cast=bool)
EMAIL_PROVIDER = config("EMAIL_PROVIDER", default="smtp")
RESEND_API_KEY = config("RESEND_API_KEY", default="")
RESEND_FROM_EMAIL = config("RESEND_FROM_EMAIL", default="")
GOOGLE_OAUTH_CLIENT_ID = config("GOOGLE_OAUTH_CLIENT_ID", default="")
GOOGLE_OAUTH_CLIENT_SECRET = config("GOOGLE_OAUTH_CLIENT_SECRET", default="")
GOOGLE_OAUTH_REDIRECT_URI = config("GOOGLE_OAUTH_REDIRECT_URI", default="")
SUPPORT_ADMIN_PASSWORD = config("SUPPORT_ADMIN_PASSWORD", default="")
SUPPORT_ATTACHMENT_MAX_BYTES = config(
    "SUPPORT_ATTACHMENT_MAX_BYTES",
    default=50 * 1024 * 1024,
    cast=int,
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*').split(',')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

PAYMENT_GATEWAY = config('PAYMENT_GATEWAY', default='wata')
WATA_HOST = config('WATA_HOST')
WATA_TOKEN = config('WATA_TOKEN')
YOOKASSA_SHOP_ID = config('YOOKASSA_SHOP_ID')
YOOKASSA_SECRET_KEY = config('YOOKASSA_SECRET_KEY')
RWMS_HOST = config('RWMS_HOST')
RWMS_PORT = config('RWMS_PORT', cast=int)

CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', 
                              default='http://localhost:8000', 
                              cast=lambda v: [s.strip() for s in v.split(',')])

EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
HAS_WHITENOISE = find_spec("whitenoise") is not None

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "engine",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if HAS_WHITENOISE:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "web_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "web_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DEFAULT_SQLITE_URL = f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
WEB_DATABASE_URL = config("WEB_DATABASE_URL", default=None)
WEB_DATABASE_SSL_REQUIRE = config("WEB_DATABASE_SSL_REQUIRE", default=False, cast=bool)

if WEB_DATABASE_URL:
    default_database_url = WEB_DATABASE_URL
elif DEBUG:
    default_database_url = DEFAULT_SQLITE_URL
else:
    raise RuntimeError(
        "WEB_DATABASE_URL must be set when DEBUG=False. "
        "Use a PostgreSQL URL like "
        "'postgresql://user:password@host:5432/web_db'."
    )

DATABASES = {
    "default": dj_database_url.parse(
        default_database_url,
        conn_max_age=600,
        ssl_require=WEB_DATABASE_SSL_REQUIRE,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ru-RU"

USE_I18N = True

USE_L10N = True  # Localization

USE_TZ = True  # Убедись, что часовые пояса тоже включены

TIME_ZONE = "Europe/Moscow"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

if HAS_WHITENOISE:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Оставляем для админки (sqlite)
    "engine.auth_backend.SQLAlchemyBackend",  # Мостик к SQLAlchemy
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": "debug.log",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "engine": {  # или название вашего приложения
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "mediafiles"
FILE_UPLOAD_MAX_MEMORY_SIZE = SUPPORT_ATTACHMENT_MAX_BYTES
DATA_UPLOAD_MAX_MEMORY_SIZE = SUPPORT_ATTACHMENT_MAX_BYTES + 1024 * 1024
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
