# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import rwmanager_pb2 as proto_dot_rwmanager__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/rwmanager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RwManagerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserByUuid = channel.unary_unary(
                '/rwmanager.RwManager/GetUserByUuid',
                request_serializer=proto_dot_rwmanager__pb2.GetUserByUuidRequest.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetUserByUsername = channel.unary_unary(
                '/rwmanager.RwManager/GetUserByUsername',
                request_serializer=proto_dot_rwmanager__pb2.GetUserByUsernameRequest.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetUserById = channel.unary_unary(
                '/rwmanager.RwManager/GetUserById',
                request_serializer=proto_dot_rwmanager__pb2.GetUserByIdRequest.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.UserResponse.FromString,
                _registered_method=True)
        self.AddUser = channel.unary_unary(
                '/rwmanager.RwManager/AddUser',
                request_serializer=proto_dot_rwmanager__pb2.AddUserRequest.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.UserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/rwmanager.RwManager/UpdateUser',
                request_serializer=proto_dot_rwmanager__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetAllUsers = channel.unary_unary(
                '/rwmanager.RwManager/GetAllUsers',
                request_serializer=proto_dot_rwmanager__pb2.GetAllUsersRequest.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.GetAllUsersReply.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/rwmanager.RwManager/DeleteUser',
                request_serializer=proto_dot_rwmanager__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.GetInbounds = channel.unary_unary(
                '/rwmanager.RwManager/GetInbounds',
                request_serializer=proto_dot_rwmanager__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.GetInboundsResponse.FromString,
                _registered_method=True)
        self.GetNodes = channel.unary_unary(
                '/rwmanager.RwManager/GetNodes',
                request_serializer=proto_dot_rwmanager__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.GetNodesResponse.FromString,
                _registered_method=True)
        self.GetNodeUsersUsage = channel.unary_unary(
                '/rwmanager.RwManager/GetNodeUsersUsage',
                request_serializer=proto_dot_rwmanager__pb2.GetNodeUsersUsageRequest.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.GetNodeUsersUsageResponse.FromString,
                _registered_method=True)
        self.GetNodeSecret = channel.unary_unary(
                '/rwmanager.RwManager/GetNodeSecret',
                request_serializer=proto_dot_rwmanager__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.GetNodeSecretResponse.FromString,
                _registered_method=True)
        self.CreateNode = channel.unary_unary(
                '/rwmanager.RwManager/CreateNode',
                request_serializer=proto_dot_rwmanager__pb2.CreateNodeRequest.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.Node.FromString,
                _registered_method=True)
        self.GetUserHwidDevices = channel.unary_unary(
                '/rwmanager.RwManager/GetUserHwidDevices',
                request_serializer=proto_dot_rwmanager__pb2.GetUserHwidDevicesRequest.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.GetUserHwidDevicesResponse.FromString,
                _registered_method=True)
        self.DeleteUserHwidDevice = channel.unary_unary(
                '/rwmanager.RwManager/DeleteUserHwidDevice',
                request_serializer=proto_dot_rwmanager__pb2.DeleteUserHwidDeviceRequest.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.DeleteUserHwidDeviceResponse.FromString,
                _registered_method=True)
        self.GetHwidSettings = channel.unary_unary(
                '/rwmanager.RwManager/GetHwidSettings',
                request_serializer=proto_dot_rwmanager__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.GetHwidSettingsResponse.FromString,
                _registered_method=True)
        self.RevokeUserSubscription = channel.unary_unary(
                '/rwmanager.RwManager/RevokeUserSubscription',
                request_serializer=proto_dot_rwmanager__pb2.RevokeUserSubscriptionRequest.SerializeToString,
                response_deserializer=proto_dot_rwmanager__pb2.UserResponse.FromString,
                _registered_method=True)


class RwManagerServicer:
    """Missing associated documentation comment in .proto file."""

    def GetUserByUuid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInbounds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodes(self, request, context):
        """Read-only статистика для поиска аномального потребления трафика
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeUsersUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeSecret(self, request, context):
        """Автоматизация установки нод через админку сайта.
        GetNodeSecret отдаёт панельный ключ (keygen), CreateNode идемпотентно
        создаёт ноду (существующая с тем же именем/адресом возвращается как есть).
        Удаления нод здесь нет намеренно (Remnawave Safety Rules).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserHwidDevices(self, request, context):
        """HWID-устройства подписки: список и удаление одного устройства из кабинета.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserHwidDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHwidSettings(self, request, context):
        """Панельные настройки HWID: нужны кабинету, чтобы показать реальный
        лимит устройств подписки, когда личный hwid_device_limit не задан.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeUserSubscription(self, request, context):
        """Перевыпуск подписки по явному действию владельца в кабинете:
        POST /api/users/{uuid}/actions/revoke панели. Ответ — обновлённый
        пользователь с новым short_uuid и subscription_url.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RwManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserByUuid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByUuid,
                    request_deserializer=proto_dot_rwmanager__pb2.GetUserByUuidRequest.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.UserResponse.SerializeToString,
            ),
            'GetUserByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByUsername,
                    request_deserializer=proto_dot_rwmanager__pb2.GetUserByUsernameRequest.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.UserResponse.SerializeToString,
            ),
            'GetUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserById,
                    request_deserializer=proto_dot_rwmanager__pb2.GetUserByIdRequest.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.UserResponse.SerializeToString,
            ),
            'AddUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUser,
                    request_deserializer=proto_dot_rwmanager__pb2.AddUserRequest.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.UserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=proto_dot_rwmanager__pb2.UpdateUserRequest.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.UserResponse.SerializeToString,
            ),
            'GetAllUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllUsers,
                    request_deserializer=proto_dot_rwmanager__pb2.GetAllUsersRequest.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.GetAllUsersReply.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=proto_dot_rwmanager__pb2.DeleteUserRequest.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.DeleteUserResponse.SerializeToString,
            ),
            'GetInbounds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInbounds,
                    request_deserializer=proto_dot_rwmanager__pb2.Empty.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.GetInboundsResponse.SerializeToString,
            ),
            'GetNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodes,
                    request_deserializer=proto_dot_rwmanager__pb2.Empty.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.GetNodesResponse.SerializeToString,
            ),
            'GetNodeUsersUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeUsersUsage,
                    request_deserializer=proto_dot_rwmanager__pb2.GetNodeUsersUsageRequest.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.GetNodeUsersUsageResponse.SerializeToString,
            ),
            'GetNodeSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeSecret,
                    request_deserializer=proto_dot_rwmanager__pb2.Empty.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.GetNodeSecretResponse.SerializeToString,
            ),
            'CreateNode': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNode,
                    request_deserializer=proto_dot_rwmanager__pb2.CreateNodeRequest.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.Node.SerializeToString,
            ),
            'GetUserHwidDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserHwidDevices,
                    request_deserializer=proto_dot_rwmanager__pb2.GetUserHwidDevicesRequest.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.GetUserHwidDevicesResponse.SerializeToString,
            ),
            'DeleteUserHwidDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserHwidDevice,
                    request_deserializer=proto_dot_rwmanager__pb2.DeleteUserHwidDeviceRequest.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.DeleteUserHwidDeviceResponse.SerializeToString,
            ),
            'GetHwidSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHwidSettings,
                    request_deserializer=proto_dot_rwmanager__pb2.Empty.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.GetHwidSettingsResponse.SerializeToString,
            ),
            'RevokeUserSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeUserSubscription,
                    request_deserializer=proto_dot_rwmanager__pb2.RevokeUserSubscriptionRequest.FromString,
                    response_serializer=proto_dot_rwmanager__pb2.UserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rwmanager.RwManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rwmanager.RwManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RwManager:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserByUuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/GetUserByUuid',
            proto_dot_rwmanager__pb2.GetUserByUuidRequest.SerializeToString,
            proto_dot_rwmanager__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/GetUserByUsername',
            proto_dot_rwmanager__pb2.GetUserByUsernameRequest.SerializeToString,
            proto_dot_rwmanager__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/GetUserById',
            proto_dot_rwmanager__pb2.GetUserByIdRequest.SerializeToString,
            proto_dot_rwmanager__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/AddUser',
            proto_dot_rwmanager__pb2.AddUserRequest.SerializeToString,
            proto_dot_rwmanager__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/UpdateUser',
            proto_dot_rwmanager__pb2.UpdateUserRequest.SerializeToString,
            proto_dot_rwmanager__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/GetAllUsers',
            proto_dot_rwmanager__pb2.GetAllUsersRequest.SerializeToString,
            proto_dot_rwmanager__pb2.GetAllUsersReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/DeleteUser',
            proto_dot_rwmanager__pb2.DeleteUserRequest.SerializeToString,
            proto_dot_rwmanager__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInbounds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/GetInbounds',
            proto_dot_rwmanager__pb2.Empty.SerializeToString,
            proto_dot_rwmanager__pb2.GetInboundsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/GetNodes',
            proto_dot_rwmanager__pb2.Empty.SerializeToString,
            proto_dot_rwmanager__pb2.GetNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeUsersUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/GetNodeUsersUsage',
            proto_dot_rwmanager__pb2.GetNodeUsersUsageRequest.SerializeToString,
            proto_dot_rwmanager__pb2.GetNodeUsersUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/GetNodeSecret',
            proto_dot_rwmanager__pb2.Empty.SerializeToString,
            proto_dot_rwmanager__pb2.GetNodeSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/CreateNode',
            proto_dot_rwmanager__pb2.CreateNodeRequest.SerializeToString,
            proto_dot_rwmanager__pb2.Node.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserHwidDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/GetUserHwidDevices',
            proto_dot_rwmanager__pb2.GetUserHwidDevicesRequest.SerializeToString,
            proto_dot_rwmanager__pb2.GetUserHwidDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserHwidDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/DeleteUserHwidDevice',
            proto_dot_rwmanager__pb2.DeleteUserHwidDeviceRequest.SerializeToString,
            proto_dot_rwmanager__pb2.DeleteUserHwidDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHwidSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/GetHwidSettings',
            proto_dot_rwmanager__pb2.Empty.SerializeToString,
            proto_dot_rwmanager__pb2.GetHwidSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeUserSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwmanager.RwManager/RevokeUserSubscription',
            proto_dot_rwmanager__pb2.RevokeUserSubscriptionRequest.SerializeToString,
            proto_dot_rwmanager__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
